import os
import json
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv(".env.local")

url = os.getenv("NEXT_PUBLIC_SUPABASE_URL") or os.getenv("SUPABASE_URL")
key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("NEXT_PUBLIC_SUPABASE_ANON_KEY") or os.getenv("SUPABASE_KEY")

if not url or not key:
    raise RuntimeError("Variáveis de ambiente não encontradas!")

supabase: Client = create_client(url, key)

# Helper para buscar o arasaac_id de uma palavra
def get_id(palavra: str):
    palavra_normalizada = palavra.strip().lower()
    res = (
        supabase.table("pictograma")
        .select("arasaac_id")
        .ilike("palavra", palavra_normalizada)
        .limit(1)
        .execute()
    )
    if res.data:
        return int(res.data[0]["arasaac_id"])
    return None

def popular_frases_reais():
    # Defina frases que realmente fazem sentido funcional
    frases_exemplo = [
    "eu querer maçã",
    "eu querer banana",
    "eu querer laranja",
    "eu querer morango",
    "eu querer pêssego",
    "eu querer melão",
    "eu querer melancia",
    "eu querer ananás",
    "eu querer pêra",
    "eu querer chocolate",
    "eu querer doce",
    "eu querer donut",
    "eu querer croissant",
    "eu querer pizza",
    "eu querer hambúrguer",
    "eu querer sandes",
    "eu querer sopa",
    "eu querer salada",
    "eu querer esparguete",
    "eu querer massa",
    "eu querer arroz com tomate",
    "eu querer pão",
    "eu querer queijo",
    "eu querer manteiga",
    "eu querer ovo",
    "eu querer carne",
    "eu querer peixe",
    "eu querer frango",
    "eu querer batatas fritas",
    "eu querer cereais",
    "eu querer bolachas",
    "eu querer água",
    "eu querer leite",
    "eu querer café",
    "eu querer chávena de café",

    "eu beber água",
    "eu beber leite",
    "eu beber café",
    "eu beber infusão",
    "eu beber chá",
    "eu comer maçã",
    "eu comer banana",
    "eu comer laranja",
    "eu comer morango",
    "eu comer pêssego",
    "eu comer melão",
    "eu comer melancia",
    "eu comer ananás",
    "eu comer pêra",
    "eu comer chocolate",
    "eu comer doce",
    "eu comer donut",
    "eu comer croissant",
    "eu comer pizza",
    "eu comer hambúrguer",
    "eu comer sandes",
    "eu comer sopa",
    "eu comer salada",
    "eu comer esparguete",
    "eu comer massa",
    "eu comer arroz com tomate",
    "eu comer pão",
    "eu comer queijo",
    "eu comer manteiga",
    "eu comer ovo",
    "eu comer carne",
    "eu comer peixe",
    "eu comer frango",
    "eu comer batatas fritas",
    "eu comer cereais",
    "eu comer bolachas",

    "eu cozinhar sopa",
    "eu cozinhar massa",
    "eu cozinhar carne",
    "eu cozinhar peixe",
    "eu cozinhar frango",
    "eu cozinhar ovo",
    "eu cozinhar arroz com tomate",
    "eu cozinhar batatas",
    "eu cozinhar legumes",
    "eu cozinhar no forno",
    "eu cozinhar no fogão",
    "eu cortar pão",
    "eu cortar carne",
    "eu cortar queijo",
    "eu cortar fruta",
    "eu cortar maçã",
    "eu cortar banana",
    "eu cortar laranja",
    "eu descascar banana",
    "eu descascar laranja",
    "eu descascar batata",
    "eu picar cebola",
    "eu misturar comida",
    "eu mexer comida",
    "eu açucarar café",
    "eu condimentar comida",
    "eu pôr a mesa",
    "eu limpar a mesa",
    "eu levantar a mesa",
    "eu lavar a loiça",
    "eu guardar pratos",
    "eu guardar comida",

    "eu abrir a porta",
    "eu fechar a porta",
    "eu abrir o armário",
    "eu fechar o armário",
    "eu abrir a janela",
    "eu fechar a janela",
    "eu abrir a caixa",
    "eu fechar a caixa",
    "eu abrir o frigorífico",
    "eu fechar o frigorífico",
    "eu ligar a televisão",
    "eu desligar a televisão",
    "eu ligar o computador",
    "eu desligar o computador",
    "eu acender a lâmpada",
    "eu apagar a lâmpada",
    "eu acender o candeeiro",
    "eu apagar o candeeiro",
    "eu acender a luz",
    "eu apagar a luz",
    "eu ligar o telefone",
    "eu desligar o telefone",

    "eu ler livro",
    "eu ler história",
    "eu ler caderno",
    "eu escrever no caderno",
    "eu escrever com caneta",
    "eu escrever com lápis",
    "eu desenhar",
    "eu desenhar uma casa",
    "eu desenhar uma árvore",
    "eu pintar",
    "eu pintar a casa",
    "eu pintar a árvore",
    "eu pintar o papel",
    "eu colar papel",
    "eu colar autocolantes",
    "eu cortar papel",
    "eu rasgar papel",
    "eu apagar com borracha",
    "eu afiar o lápis",
    "eu guardar o lápis",
    "eu guardar a caneta",
    "eu guardar o livro",
    "eu guardar o caderno",
    "eu arrumar o caderno",
    "eu arrumar o quarto",

    "eu estudar em casa",
    "eu estudar na escola",
    "eu trabalhar em casa",
    "eu trabalhar na escola",
    "eu jogar em casa",
    "eu jogar no jardim",
    "eu jogar no parque",
    "eu jogar futebol",
    "eu jogar bowling",
    "eu jogar ludo",
    "eu jogar pingue-pongue",
    "eu jogar com a bola",
    "eu jogar com a raquete",
    "eu jogar com o puzzle",
    "eu montar o puzzle",
    "eu tocar piano",
    "eu tocar guitarra",
    "eu tocar flauta",
    "eu tocar saxofone",
    "eu tocar tambor",
    "eu tocar pandeiro",
    "eu cantar música",
    "eu ouvir música",
    "eu ouvir rádio",
    "eu ver televisão",
    "eu ver filme",
    "eu ver desenho",

    "eu andar de bicicleta",
    "eu andar de trotinete",
    "eu andar de skate",
    "eu andar de patins",
    "eu passear",
    "eu passear no jardim",
    "eu passear no parque",
    "eu passear na rua",
    "eu caminhar",
    "eu correr",
    "eu saltar",
    "eu saltar à corda",
    "eu subir a escada",
    "eu descer a escada",
    "eu entrar no carro",
    "eu sair do carro",
    "eu entrar no autocarro",
    "eu sair do autocarro",
    "eu entrar no avião",
    "eu viajar de avião",
    "eu viajar de barco",
    "eu viajar de comboio",
    "eu conduzir o carro",
    "eu estacionar o carro",

    "eu tomar banho",
    "eu tomar duche",
    "eu lavar as mãos",
    "eu lavar a cara",
    "eu lavar os dentes",
    "eu escovar os dentes",
    "eu ensaboar as mãos",
    "eu ensaboar a cara",
    "eu pentear o cabelo",
    "eu secar o cabelo",
    "eu vestir a camisola",
    "eu vestir a camisa",
    "eu vestir as calças",
    "eu vestir o casaco",
    "eu vestir o pijama",
    "eu calçar as botas",
    "eu calçar as meias",
    "eu calçar as sandálias",
    "eu tirar o casaco",
    "eu tirar as botas",
    "eu tirar as meias",
    "eu passar o creme",
    "eu pintar as unhas",
    "eu fazer a cama",
    "eu arrumar a cama",
    "eu lavar a roupa",
    "eu secar a roupa",
    "eu passar a ferro",

    "eu limpar a casa",
    "eu limpar o quarto",
    "eu limpar a mesa",
    "eu limpar o chão",
    "eu varrer o chão",
    "eu aspirar a carpete",
    "eu limpar o pó",
    "eu arrumar o armário",
    "eu arrumar os brinquedos",
    "eu guardar os brinquedos",
    "eu guardar a roupa",
    "eu guardar os sapatos",
    "eu lavar a roupa",
    "eu pôr a roupa",
    "eu retirar a roupa",

    "eu regar a planta",
    "eu plantar uma árvore",
    "eu plantar flores",
    "eu cheirar a flor",
    "eu ver a árvore",
    "eu ver a flor",
    "eu ver o jardim",
    "eu cuidar da planta",
    "eu cavar a terra",
    "eu molhar a planta",

    "eu ver o cão",
    "eu ver o gato",
    "eu ver o cavalo",
    "eu ver a cabra",
    "eu ver o burro",
    "eu ver a ovelha",
    "eu ver o porco",
    "eu ver a galinha",
    "eu ver o galo",
    "eu ver o pato",
    "eu ver o coelho",
    "eu ver o rato",
    "eu ver o esquilo",
    "eu ver a borboleta",
    "eu ver a abelha",
    "eu ver a aranha",
    "eu ver a formiga",
    "eu ver a mosca",
    "eu ver o mosquito",
    "eu ver a baleia",
    "eu ver o peixe",
    "eu ver o tubarão",
    "eu ver o caranguejo",
    "eu ver a foca",
    "eu ver o crocodilo",
    "eu ver a serpente",
    "eu ver o elefante",
    "eu ver a girafa",
    "eu ver o leão",
    "eu ver o tigre",
    "eu ver o macaco",
    "eu ver o gorila",
    "eu ver o hipopótamo",
    "eu ver o rinoceronte",
    "eu ver o canguru",
    "eu ver a zebra",
    "eu ver o papagaio",
    "eu ver o periquito",
    "eu ver a pomba",
    "eu ver o pássaro",
    "eu ver o urso",
    "eu ver o dromedário",

    "eu gostar de animais",
    "eu gostar de música",
    "eu gostar de futebol",
    "eu gostar de chocolate",
    "eu gostar de pizza",
    "eu gostar de praia",
    "eu gostar de brincar",
    "eu gostar de livros",
    "eu gostar de televisão",
    "eu gostar de jogos",
    "eu gostar de bicicleta",
    "eu gostar de cães",
    "eu gostar de gatos",

    "eu estar cansado",
    "eu estar triste",
    "eu estar assustado",
    "eu estar aborrecido",
    "eu estar chateado",
    "eu estar confuso",
    "eu estar enjoado",
    "eu estar surpreendido",
    "eu estar esfomeado",
    "eu estar sedento",
    "eu estar quente",
    "eu estar frio",
    "eu estar molhado",
    "eu estar seco",
    "eu estar feliz",
    "eu estar sozinho",
    "eu estar dentro",
    "eu estar fora",
    "eu estar em casa",
    "eu estar na escola",

    "eu querer ajuda",
    "eu precisar de ajuda",
    "eu precisar de água",
    "eu precisar de comida",
    "eu precisar de um médico",
    "eu precisar da enfermeira",
    "eu precisar do professor",
    "eu precisar da professora",
    "eu querer descansar",
    "eu querer dormir",
    "eu querer brincar",
    "eu querer sair",
    "eu querer entrar",
    "eu querer ir para casa",
    "eu querer ir para a escola",
    "eu querer ir ao parque",
    "eu querer ir ao jardim",

    "eu ter dor",
    "eu ter fome",
    "eu ter sede",
    "eu ter medo",
    "eu ter frio",
    "eu ter calor",
    "eu ter sono",
    "eu ter uma ideia",
    "eu ter um livro",
    "eu ter uma bola",
    "eu ter uma bicicleta",
    "eu ter um computador",
    "eu ter um telefone",
    "eu ter uma mochila",
    "eu ter uma caneta",
    "eu ter um lápis",
    "eu ter uma borracha",

    "ele beber água",
    "ele beber leite",
    "ele beber café",
    "ele comer maçã",
    "ele comer banana",
    "ele comer chocolate",
    "ele comer pão",
    "ele comer pizza",
    "ele comer carne",
    "ele comer peixe",
    "ele comer sopa",
    "ele cozinhar",
    "ele estudar",
    "ele ler livro",
    "ele escrever no caderno",
    "ele pintar",
    "ele desenhar",
    "ele jogar futebol",
    "ele jogar bowling",
    "ele tocar piano",
    "ele cantar",
    "ele ouvir música",
    "ele ver televisão",
    "ele correr",
    "ele saltar",
    "ele andar de bicicleta",
    "ele passear",
    "ele viajar",
    "ele trabalhar",
    "ele dormir",
    "ele acordar",
    "ele entrar em casa",
    "ele sair de casa",
    "ele abrir a porta",
    "ele fechar a porta",
    "ele acender a luz",
    "ele apagar a luz",
    "ele tomar banho",
    "ele escovar os dentes",
    "ele vestir roupa",
    "ele limpar a casa",
    "ele arrumar o quarto",
    "ele cozinhar no forno",
    "ele cozinhar no fogão",
    "ele lavar a roupa",
    "ele regar a planta",
    "ele plantar uma árvore",
    "ele ajudar mãe",
    "ele ajudar pai",
    "ele visitar avó",
    "ele visitar avô",
    "ele telefonar para mãe",
    "ele telefonar para pai",

    "ela beber água",
    "ela beber leite",
    "ela beber café",
    "ela comer maçã",
    "ela comer banana",
    "ela comer chocolate",
    "ela comer pão",
    "ela comer pizza",
    "ela comer carne",
    "ela comer peixe",
    "ela comer sopa",
    "ela cozinhar",
    "ela estudar",
    "ela ler livro",
    "ela escrever no caderno",
    "ela pintar",
    "ela desenhar",
    "ela jogar futebol",
    "ela jogar bowling",
    "ela tocar piano",
    "ela cantar",
    "ela ouvir música",
    "ela ver televisão",
    "ela correr",
    "ela saltar",
    "ela andar de bicicleta",
    "ela passear",
    "ela viajar",
    "ela trabalhar",
    "ela dormir",
    "ela acordar",
    "ela entrar em casa",
    "ela sair de casa",
    "ela abrir a porta",
    "ela fechar a porta",
    "ela acender a luz",
    "ela apagar a luz",
    "ela tomar banho",
    "ela escovar os dentes",
    "ela vestir roupa",
    "ela limpar a casa",
    "ela arrumar o quarto",
    "ela cozinhar no forno",
    "ela cozinhar no fogão",
    "ela lavar a roupa",
    "ela regar a planta",
    "ela plantar uma árvore",
    "ela ajudar mãe",
    "ela ajudar pai",
    "ela visitar avó",
    "ela visitar avô",
    "ela telefonar para mãe",
    "ela telefonar para pai",

    "nós beber água",
    "nós beber leite",
    "nós comer comida",
    "nós comer pizza",
    "nós comer chocolate",
    "nós cozinhar",
    "nós estudar",
    "nós ler livros",
    "nós escrever",
    "nós desenhar",
    "nós pintar",
    "nós jogar futebol",
    "nós jogar bowling",
    "nós cantar",
    "nós ouvir música",
    "nós ver televisão",
    "nós correr",
    "nós saltar",
    "nós andar de bicicleta",
    "nós passear",
    "nós viajar",
    "nós trabalhar",
    "nós dormir",
    "nós tomar banho",
    "nós escovar os dentes",
    "nós vestir roupa",
    "nós limpar a casa",
    "nós arrumar o quarto",
    "nós cozinhar no forno",
    "nós cozinhar no fogão",
    "nós lavar a roupa",
    "nós regar as plantas",
    "nós plantar árvores",
    "nós visitar avó",
    "nós visitar avô",
    "nós ajudar mãe",
    "nós ajudar pai",
    "nós ir para casa",
    "nós ir para escola",
    "nós ir para o parque",
    "nós ir para o jardim",

    "eles beber água",
    "eles beber leite",
    "eles comer comida",
    "eles comer pizza",
    "eles comer chocolate",
    "eles cozinhar",
    "eles estudar",
    "eles ler livros",
    "eles escrever",
    "eles desenhar",
    "eles pintar",
    "eles jogar futebol",
    "eles jogar bowling",
    "eles cantar",
    "eles ouvir música",
    "eles ver televisão",
    "eles correr",
    "eles saltar",
    "eles andar de bicicleta",
    "eles passear",
    "eles viajar",
    "eles trabalhar",
    "eles dormir",
    "eles tomar banho",
    "eles escovar os dentes",
    "eles vestir roupa",
    "eles limpar a casa",
    "eles arrumar o quarto",
    "eles cozinhar no forno",
    "eles cozinhar no fogão",
    "eles lavar a roupa",
    "eles regar as plantas",
    "eles plantar árvores",
    "eles visitar avó",
    "eles visitar avô",
    "eles ajudar mãe",
    "eles ajudar pai",
    "eles ir para casa",
    "eles ir para escola",
    "eles ir para o parque",
    "eles ir para o jardim",

    "mãe cozinhar comida",
    "mãe beber café",
    "mãe comer pão",
    "mãe ler livro",
    "mãe trabalhar",
    "mãe limpar casa",
    "mãe lavar roupa",
    "mãe arrumar casa",
    "mãe ajudar bebé",
    "mãe telefonar",
    "pai cozinhar comida",
    "pai beber café",
    "pai comer pão",
    "pai ler livro",
    "pai trabalhar",
    "pai limpar casa",
    "pai lavar roupa",
    "pai arrumar casa",
    "pai ajudar bebé",
    "pai telefonar",
    "avó cozinhar comida",
    "avó beber café",
    "avó comer pão",
    "avó ler livro",
    "avó trabalhar",
    "avó ajudar bebé",
    "avó telefonar",
    "avô beber café",
    "avô comer pão",
    "avô ler livro",
    "avô trabalhar",
    "avô ajudar bebé",
    "avô telefonar",
    "irmão jogar futebol",
    "irmão jogar bola",
    "irmão andar de bicicleta",
    "irmão estudar",
    "irmão ler livro",
    "irmão brincar",
    "irmã jogar futebol",
    "irmã jogar bola",
    "irmã andar de bicicleta",
    "irmã estudar",
    "irmã ler livro",
    "irmã brincar",

    "o cão comer comida",
    "o cão beber água",
    "o cão dormir",
    "o cão correr",
    "o cão brincar",
    "o cão entrar em casa",
    "o cão sair de casa",
    "o gato comer comida",
    "o gato beber água",
    "o gato dormir",
    "o gato correr",
    "o gato brincar",
    "o gato entrar em casa",
    "o gato sair de casa",
    "o cavalo comer",
    "o cavalo beber água",
    "o cavalo correr",
    "a galinha comer",
    "a galinha beber água",
    "o peixe nadar",
    "o pássaro voar",
    "a abelha voar",
    "a borboleta voar",
    "a aranha andar",
    "o coelho comer",
    "o coelho saltar",
    "o macaco comer banana",
    "o urso comer",
    "o leão comer carne",
    "o tigre comer carne",

    "água fria",
    "água quente",
    "café quente",
    "comida quente",
    "comida fria",
    "comida doce",
    "comida salgada",
    "comida picante",
    "maçã vermelha",
    "maçã verde",
    "banana amarela",
    "casa grande",
    "casa pequena",
    "casa bonita",
    "casa nova",
    "casa velha",
    "carro grande",
    "carro pequeno",
    "carro novo",
    "carro velho",
    "bola grande",
    "bola pequena",
    "cão grande",
    "cão pequeno",
    "gato grande",
    "gato pequeno",
    "livro grande",
    "livro pequeno",
    "mochila grande",
    "mochila pequena",
    "mesa grande",
    "mesa pequena",
    "quarto grande",
    "quarto pequeno",
    "armário grande",
    "armário pequeno",
    "roupa limpa",
    "roupa suja",
    "roupa nova",
    "roupa velha",
    "cama limpa",
    "cama arrumada",
    "casa limpa",
    "casa suja",
    "porta aberta",
    "porta fechada",
    "janela aberta",
    "janela fechada",
    "luz acesa",
    "luz apagada",

    "onde está a água?",
    "onde está a comida?",
    "onde está o livro?",
    "onde está a bola?",
    "onde está a mochila?",
    "onde está o cão?",
    "onde está o gato?",
    "onde está a mãe?",
    "onde está o pai?",
    "onde está a avó?",
    "onde está o avô?",
    "onde está a professora?",
    "onde está o professor?",
    "onde está a casa?",
    "onde está o carro?",
    "onde está a bicicleta?",
    "onde está o telefone?",
    "onde está o computador?",
    "onde está a caneta?",
    "onde está o lápis?",
    "onde está a borracha?",
    "quem é?",
    "o que é?",
    "o que estás a fazer?",
    "o que estás a comer?",
    "o que estás a beber?",
    "o que estás a ver?",
    "o que estás a ler?",
    "o que tens?",
    "onde vamos?",
    "quanto custa?",
    "posso?",
    "preciso de ajuda",
    "não sei",
    "não quero",
    "por favor",
    "obrigado",
    "olá",
    "adeus",
    "bom dia",
    "boa tarde",
    "boa noite",
    "bem-vindo",

    "eu quero este",
    "eu quero aquele",
    "eu quero isso",
    "eu não quero isso",
    "eu quero mais",
    "eu quero menos",
    "eu quero tudo",
    "eu não quero nada",
    "eu quero muito",
    "eu quero pouco",
    "eu gostar muito",
    "eu gostar pouco",
    "eu não gostar",
    "eu saber",
    "eu não saber",
    "eu poder",
    "eu não poder",
    "eu querer ir",
    "eu não querer ir",
    "eu querer ficar",
    "eu querer sair",
    "eu querer entrar",
    "eu querer parar",
    "eu querer começar",
    "eu querer acabar",
    "eu querer ajuda",
    "eu precisar de ajuda",
    "eu estar bem",
    "eu estar mal",

    "ele estar cansado",
    "ele estar triste",
    "ele estar assustado",
    "ele estar chateado",
    "ele estar confuso",
    "ele estar esfomeado",
    "ele estar sedento",
    "ela estar cansada",
    "ela estar triste",
    "ela estar assustada",
    "ela estar chateada",
    "ela estar confusa",
    "ela estar esfomeada",
    "ela estar sedenta",
    "nós estar cansado",
    "nós estar triste",
    "nós estar assustado",
    "nós estar esfomeado",
    "nós estar sedento",
    "eles estar cansados",
    "eles estar tristes",
    "eles estar assustados",
    "eles estar esfomeados",
    "eles estar sedentos"
]

    novas_frases = []

    for frase in frases_exemplo:
        palavras = frase.split()

        if len(palavras) < 2:
            print(f"Aviso: '{frase}' ignorada porque precisa ter pelo menos sujeito e verbo.")
            continue

        ids = [get_id(palavra) for palavra in palavras]

        # Apenas adiciona se todas as palavras existirem no seu banco
        if all(ids):
            lista_formatada = json.dumps(ids)
            novas_frases.append({"lista_pictograma": lista_formatada})
        else:
            faltando = [
                palavra
                for palavra, id_pictograma in zip(palavras, ids)
                if not id_pictograma
            ]
            print(
                f"Aviso: {', '.join(faltando)} de '{frase}' não foi encontrada"
                " na tabela 'pictograma'."
            )

    if novas_frases:
        res = supabase.table("frase_pictograma").insert(novas_frases).execute()
        print(f"Sucesso! {len(res.data)} frases reais e com sentido foram salvas.")
    else:
        print("Nenhuma frase pôde ser gerada. Verifique se as palavras existem na tabela 'pictograma'.")

if __name__ == "__main__":
    popular_frases_reais()
